name: Java CI with Gradle

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: aws
    steps:
       - uses: actions/checkout@v3
       - name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
           java-version: '17'
           distribution: 'temurin'
       - name: Build with Gradle
         run: |
           ./gradlew build
       - name: Unzip the target folder
         run: |
           unzip ./build/distributions/simple-gradle-java-app.zip
           cp ./simple-gradle-java-app/lib/simple-gradle-java-app.jar ${{ github.workspace }}/simple-gradle-java-app.jar
               
       - name: Login to Dockerhub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
